name: my-lando-app
recipe: drupal8
config:
  webroot: docroot
  # drush: path:/app/vendor/bin/drush
  database: mariadb
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/acquia/blt/bin/blt
proxy:
  mailhog:
    - mail.mylandoapp.lndo.site
  phpmyadmin:
    - pma.mylandoapp.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
  appserver:
    run:
      - cd $LANDO_WEBROOT && composer install
      - cd $LANDO_WEBROOT && blt setup
events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install
    - appserver: cd $LANDO_WEBROOT && blt drupal:update
