name: my-lando-app
recipe: drupal8
config:
  webroot: docroot
  # drush: path:/app/vendor/bin/drush
  database: mariadb
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/acquia/blt/bin/blt
proxy:
  mailhog:
    - mail.mylandoapp.lndo.site
  phpmyadmin:
    - pma.mylandoapp.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && /app/vendor/bin/blt blt:init:settings
      - cd $LANDO_MOUNT && drush @self.local sql-cli < initSite.sql
      - cd $LANDO_MOUNT && drush @self.local updb -y
      - cd $LANDO_MOUNT && drush @self.local cim -y
      - cd $LANDO_MOUNT && drush @self.local cr
events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install
    - appserver: cd $LANDO_MOUNT && /app/vendor/bin/blt blt:init:settings
    - appserver: cd $LANDO_MOUNT && drush @self.local updb -y
    - appserver: cd $LANDO_MOUNT && drush @self.local cim -y
    - appserver: cd $LANDO_MOUNT && drush @self.local cr
